<?php

namespace AppBundle\Repository;

/**
 * CaisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaisseRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCaisseTotal()
    {
        $query = "SELECT SUM(amount)
                  AS total    
                  FROM caisse";
        $connection = $this->_em->getConnection();
        $statement = $connection->executeQuery($query);
        return $statement->fetchColumn(0);
    }
}
